# -*- coding: utf-8 -*-
"""IA-generativa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHz02p4doUsLc60noBjqW3zwVW2sLmkG
"""

!pip install torch diffusers transformers

import torch
from diffusers import StableDiffusionPipeline
from PIL import Image
from io import BytesIO

# Cargar el modelo de Stable Diffusion
pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4")
pipe.to("cuda")  # Si tienes una GPU en Colab

# Función para generar y mostrar la imagen
def generar_imagen(texto):
    # Generar imagen
    imagen = pipe(texto).images[0]
    # Mostrar la imagen
    display(imagen)
    return imagen

# Ejemplo de uso
texto = "A fantasy landscape with mountains and rivers, sunset lighting"
generar_imagen(texto)

# Guardar la imagen en un archivo
imagen_generada = generar_imagen(texto)
imagen_generada.save("imagen_generada.png")

from google.colab import drive
drive.mount('/content/drive')

# Guardar en una carpeta en Google Drive
imagen_generada.save("/content/drive/MyDrive/imagenes/imagen_generada.png")